-- Baseline: every table as lib/db/schema.ts declares it, generated by drizzle-kit and then made
-- idempotent by hand (`if not exists`, constraints in `exception when duplicate_object` blocks).
-- On a database set up with the SQL files that came before Drizzle (supabase/ai-filter.sql and
-- supabase/scraping.sql, in git history) it changes nothing; on an empty one it creates everything.
-- scripts/db-verify-migrations.sh checks both.
-- Keep it that way: this file may already have run on production as written. Every change after
-- it is a new migration (`npm run db:generate`).

CREATE TABLE IF NOT EXISTS "ai_dup_pairs" (
	"key_a" text NOT NULL,
	"key_b" text NOT NULL,
	"same" boolean NOT NULL,
	"reason" text,
	"model" text,
	"decided_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_dup_pairs_pkey" PRIMARY KEY("key_a","key_b"),
	CONSTRAINT "ai_dup_pairs_check" CHECK (key_a < key_b)
);
--> statement-breakpoint
ALTER TABLE "ai_dup_pairs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ai_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"prompt" text DEFAULT '' NOT NULL,
	"file_name" text,
	"file_text" text,
	"version" integer DEFAULT 1 NOT NULL,
	"last_used_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ai_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ai_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"profile_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"label" text NOT NULL,
	"range_gte" timestamp with time zone,
	"range_lt" timestamp with time zone,
	"status" text DEFAULT 'running' NOT NULL,
	"total" integer DEFAULT 0 NOT NULL,
	"done" integer DEFAULT 0 NOT NULL,
	"error" text,
	"lock_until" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"phase" text DEFAULT 'dedup' NOT NULL,
	"pairs_checked" integer DEFAULT 0 NOT NULL,
	"merged" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "ai_runs_status_check" CHECK (status in ('running', 'done', 'failed', 'cancelled'))
);
--> statement-breakpoint
ALTER TABLE "ai_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ai_verdicts" (
	"profile_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"dup_key" text NOT NULL,
	"match" boolean NOT NULL,
	"score" integer NOT NULL,
	"summary" text,
	"checks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"had_description" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_verdicts_pkey" PRIMARY KEY("profile_id","version","dup_key"),
	CONSTRAINT "ai_verdicts_score_check" CHECK (score between 0 and 100)
);
--> statement-breakpoint
ALTER TABLE "ai_verdicts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "applications" (
	"dup_key" text PRIMARY KEY NOT NULL,
	"src" text NOT NULL,
	"id" text NOT NULL,
	"title" text NOT NULL,
	"company" text,
	"url" text NOT NULL,
	"applied_at" timestamp with time zone DEFAULT now() NOT NULL,
	"content" text,
	"details" jsonb,
	"content_status" text DEFAULT 'pending' NOT NULL,
	"content_error" text,
	"scraped_at" timestamp with time zone,
	"stage" text DEFAULT 'submitted' NOT NULL,
	"stage_state" text DEFAULT 'pending' NOT NULL,
	"stage_updated_at" timestamp with time zone,
	"history" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"note" text,
	"note_updated_at" timestamp with time zone,
	CONSTRAINT "applications_content_status_check" CHECK (content_status in ('pending', 'ok', 'empty', 'failed')),
	CONSTRAINT "applications_stage_check" CHECK (stage in ('submitted', 'invited', 'screening', 'technical', 'hr', 'offer')),
	CONSTRAINT "applications_stage_state_check" CHECK (stage_state in ('pending', 'passed', 'failed', 'ghosted', 'pool')),
	CONSTRAINT "applications_note_length" CHECK (length(note) <= 10000)
);
--> statement-breakpoint
ALTER TABLE "applications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_links" (
	"dup_key" text PRIMARY KEY NOT NULL,
	"job_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "job_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "notify_queue" (
	"src" text NOT NULL,
	"id" text NOT NULL,
	"title" text NOT NULL,
	"company" text,
	"seniority" text,
	"remote" boolean,
	"location" text,
	"url" text NOT NULL,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"dup_key" text,
	CONSTRAINT "notify_queue_pkey" PRIMARY KEY("src","id")
);
--> statement-breakpoint
ALTER TABLE "notify_queue" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "offer_details" (
	"src" text NOT NULL,
	"id" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "offer_details_pkey" PRIMARY KEY("src","id"),
	CONSTRAINT "offer_details_status_check" CHECK (status in ('ok', 'empty'))
);
--> statement-breakpoint
ALTER TABLE "offer_details" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "offers" (
	"src" text NOT NULL,
	"id" text NOT NULL,
	"title" text NOT NULL,
	"company" text,
	"seniority" text,
	"remote" boolean,
	"url" text NOT NULL,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL,
	"dup_key" text GENERATED ALWAYS AS (public.jw_dup_key(company, title)) STORED,
	CONSTRAINT "offers_pkey" PRIMARY KEY("src","id")
);
--> statement-breakpoint
ALTER TABLE "offers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scrape_runs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "scrape_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"trigger" text NOT NULL,
	"found" integer DEFAULT 0 NOT NULL,
	"kept" integer DEFAULT 0 NOT NULL,
	"added" integer DEFAULT 0 NOT NULL,
	"fresh" integer DEFAULT 0 NOT NULL,
	"notified" integer DEFAULT 0 NOT NULL,
	"errors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"matched" integer
);
--> statement-breakpoint
ALTER TABLE "scrape_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scrape_seeds" (
	"name" text PRIMARY KEY NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "scrape_seeds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scrape_settings" (
	"id" boolean PRIMARY KEY DEFAULT true NOT NULL,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "scrape_settings_id_check" CHECK (id)
);
--> statement-breakpoint
ALTER TABLE "scrape_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scrape_state" (
	"id" boolean PRIMARY KEY DEFAULT true NOT NULL,
	"locked_until" timestamp with time zone,
	"last_call_at" timestamp with time zone,
	"last_run_at" timestamp with time zone,
	"muted" boolean DEFAULT false NOT NULL,
	CONSTRAINT "scrape_state_id_check" CHECK (id)
);
--> statement-breakpoint
ALTER TABLE "scrape_state" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scrapers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"name" text NOT NULL,
	"src" text NOT NULL,
	"kind" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"mark" double precision,
	"last_run_at" timestamp with time zone,
	"last_status" text,
	"last_found" integer,
	"last_kept" integer,
	"last_new" integer,
	"last_error" text,
	"last_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "scrapers_src_check" CHECK (src ~ '^[a-z0-9][a-z0-9_-]{0,29}$'),
	CONSTRAINT "scrapers_kind_check" CHECK (kind in ('justjoin', 'nofluff', 'solidjobs', 'bulldog', 'eldorado', 'builtin', 'linkedin', 'json', 'html', 'rss')),
	CONSTRAINT "scrapers_status_check" CHECK (last_status in ('ok', 'error'))
);
--> statement-breakpoint
ALTER TABLE "scrapers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
-- Columns and checks those SQL files added to existing tables with `alter table`. A database
-- they set up already has them (no-op); one that missed a later run of the files gets them now.
-- The checks are replaced, as the files did, so each has its latest definition.
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "dup_key" text GENERATED ALWAYS AS (public.jw_dup_key(company, title)) STORED;--> statement-breakpoint
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "stage" text DEFAULT 'submitted' NOT NULL;--> statement-breakpoint
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "stage_state" text DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "stage_updated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "history" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "note" text;--> statement-breakpoint
ALTER TABLE "applications" ADD COLUMN IF NOT EXISTS "note_updated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "ai_runs" ADD COLUMN IF NOT EXISTS "phase" text DEFAULT 'dedup' NOT NULL;--> statement-breakpoint
ALTER TABLE "ai_runs" ADD COLUMN IF NOT EXISTS "pairs_checked" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "ai_runs" ADD COLUMN IF NOT EXISTS "merged" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "notify_queue" ADD COLUMN IF NOT EXISTS "dup_key" text;--> statement-breakpoint
ALTER TABLE "scrape_runs" ADD COLUMN IF NOT EXISTS "matched" integer;--> statement-breakpoint
ALTER TABLE "applications" DROP CONSTRAINT IF EXISTS "applications_stage_check";--> statement-breakpoint
ALTER TABLE "applications" ADD CONSTRAINT "applications_stage_check" CHECK (stage in ('submitted', 'invited', 'screening', 'technical', 'hr', 'offer'));--> statement-breakpoint
ALTER TABLE "applications" DROP CONSTRAINT IF EXISTS "applications_stage_state_check";--> statement-breakpoint
ALTER TABLE "applications" ADD CONSTRAINT "applications_stage_state_check" CHECK (stage_state in ('pending', 'passed', 'failed', 'ghosted', 'pool'));--> statement-breakpoint
ALTER TABLE "applications" DROP CONSTRAINT IF EXISTS "applications_note_length";--> statement-breakpoint
ALTER TABLE "applications" ADD CONSTRAINT "applications_note_length" CHECK (length(note) <= 10000);--> statement-breakpoint
ALTER TABLE "scrapers" DROP CONSTRAINT IF EXISTS "scrapers_src_check";--> statement-breakpoint
ALTER TABLE "scrapers" ADD CONSTRAINT "scrapers_src_check" CHECK (src ~ '^[a-z0-9][a-z0-9_-]{0,29}$');--> statement-breakpoint
ALTER TABLE "scrapers" DROP CONSTRAINT IF EXISTS "scrapers_kind_check";--> statement-breakpoint
ALTER TABLE "scrapers" ADD CONSTRAINT "scrapers_kind_check" CHECK (kind in ('justjoin', 'nofluff', 'solidjobs', 'bulldog', 'eldorado', 'builtin', 'linkedin', 'json', 'html', 'rss'));--> statement-breakpoint
ALTER TABLE "scrapers" DROP CONSTRAINT IF EXISTS "scrapers_status_check";--> statement-breakpoint
ALTER TABLE "scrapers" ADD CONSTRAINT "scrapers_status_check" CHECK (last_status in ('ok', 'error'));--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "ai_runs" ADD CONSTRAINT "ai_runs_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."ai_profiles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "ai_verdicts" ADD CONSTRAINT "ai_verdicts_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."ai_profiles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "offer_details" ADD CONSTRAINT "offer_details_src_id_fkey" FOREIGN KEY ("src","id") REFERENCES "public"."offers"("src","id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_runs_profile_idx" ON "ai_runs" USING btree ("profile_id","created_at" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "applications_applied_at_idx" ON "applications" USING btree ("applied_at" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "job_links_job_key_idx" ON "job_links" USING btree ("job_key");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "offers_first_seen_idx" ON "offers" USING btree ("first_seen" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "offers_dup_key_idx" ON "offers" USING btree ("dup_key","first_seen");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scrape_runs_started_idx" ON "scrape_runs" USING btree ("started_at" DESC NULLS FIRST);