-- ⚠️ HISTORICAL, NOT A MIGRATION. Kept for reference; don't run it on today's database.
--
-- When: 2026-10-02, once, by hand in Supabase → SQL Editor, before the app could tell duplicates
-- apart. Early scrapers had saved the same job several times: on several boards, re-posted on one,
-- and old Eldorado rows with a broken src. This script is a snapshot of that database: it lists
-- 523 specific rows by id, so it only ever made sense on that data.
-- Since then: offers.dup_key + the offers_unique view show every job once without deleting
-- anything, and AI merges (job_links, lib/dedup.ts) handle the near-duplicates. The schema itself
-- is managed by the migrations in drizzle/ (npm run db:migrate).
-- It left behind public.offers_removed_dupes (the removed rows, for an undo). That table isn't in
-- lib/db/schema.ts; drizzle-kit ignores it, and it can be dropped once nobody needs the undo.
--
-- The original header follows.
--
-- One-off cleanup of the offers table. Supabase -> SQL Editor -> paste -> Run.
-- Generated 2026-10-02T14:51Z from the 1398 stored offers.
--
-- 1. Old Eldorado offers saved by an early scraper version with a broken source (digits
--    instead of "eldorado"): drop the copy if the proper eldorado row exists, else fix src.
-- 2. Duplicates (523): same company + title on another board, or re-posted on the
--    same one. Keeps the earliest-seen copy of each job (875 jobs).
--
-- Everything removed is copied to offers_removed_dupes first. Undo:
--   insert into public.offers (src, id, title, company, seniority, remote, url, first_seen)
--   select src, id, title, company, seniority, remote, url, first_seen from public.offers_removed_dupes on conflict do nothing;
-- Optional since supabase/ai-filter.sql: the app already shows every job once (offers_unique).
-- Everything runs in one transaction: if any step fails, nothing changes.

begin;

-- explicit columns: offers.dup_key (added by ai-filter.sql) is computed and can't be copied
create table if not exists public.offers_removed_dupes (
  src text not null, id text not null, title text not null, company text, seniority text,
  remote boolean, url text not null, first_seen timestamptz not null,
  primary key (src, id)
);
alter table public.offers_removed_dupes enable row level security;

-- 1a. broken-source copies of rows that also exist properly
with gone as (
  delete from public.offers o
  where o.src ~ '^[0-9]+$'
    and exists (select 1 from public.offers e where e.src = 'eldorado' and e.id = o.id)
  returning o.src, o.id, o.title, o.company, o.seniority, o.remote, o.url, o.first_seen
)
insert into public.offers_removed_dupes (src, id, title, company, seniority, remote, url, first_seen)
select src, id, title, company, seniority, remote, url, first_seen from gone on conflict do nothing;

-- 1b. the rest of the broken-source rows are real eldorado offers
update public.offers set src = 'eldorado' where src ~ '^[0-9]+$';

-- 2. duplicates
with dupes(src, id) as (values
  ('eldorado', '436250'),
  ('eldorado', '436026'),
  ('eldorado', '435700'),
  ('eldorado', '436163'),
  ('eldorado', '435554'),
  ('eldorado', '435961'),
  ('eldorado', '436022'),
  ('eldorado', '436208'),
  ('eldorado', '435629'),
  ('eldorado', '436181'),
  ('eldorado', '436303'),
  ('eldorado', '436895'),
  ('eldorado', '436762'),
  ('eldorado', '436727'),
  ('eldorado', '437308'),
  ('nofluff', 'frontend-developer-m-f-grupa-pracuj-Remote'),
  ('eldorado', '439496'),
  ('eldorado', '434293'),
  ('justjoin', 'sorigo-fullstack-developer-developerka-java-react--warszawa-java'),
  ('justjoin', 'ness-solution-senior-java-developer-warszawa-java-fece85ff'),
  ('eldorado', '444271'),
  ('justjoin', 'jit-team-senior-fullstack-developer-java-react--warszawa-java-32b39922'),
  ('eldorado', '437791'),
  ('eldorado', '437212'),
  ('eldorado', '437620'),
  ('eldorado', '437310'),
  ('justjoin', 'connectis-fullstack-developer-node-js-warszawa-javascript'),
  ('justjoin', '7n-sp-z-o-o--fullstack-developer-java-react--gdansk-java'),
  ('eldorado', '437287'),
  ('justjoin', 'emagine-polska-java-developer-warszawa-java-5062c5ac'),
  ('eldorado', '436303'),
  ('justjoin', 'apreel-senior-fullstack-java-developer-warszawa-java-890e860b'),
  ('bulldog', '255361-full-stack-engineer-warsaw-sensor-tower'),
  ('bulldog', '255360-full-stack-engineer-krakow-sensor-tower'),
  ('bulldog', '255370-full-stack-engineer-warsaw-salespatriot'),
  ('bulldog', '255367-senior-software-engineer-krakow-intellistack'),
  ('justjoin', 'the-software-house-senior-fullstack-developer-node-js-blockchain--gliwice-javascript'),
  ('justjoin', 'bluesoft-react-developer-warszawa-javascript-d590d65a'),
  ('justjoin', 'bluesoft-react-developer-warszawa-javascript-195afbdc'),
  ('justjoin', 'bluesoft-react-developer-warszawa-javascript-5f9e8eec'),
  ('justjoin', 'bluesoft-react-developer-warszawa-javascript-e65b7cab'),
  ('eldorado', '435629'),
  ('justjoin', 'creotech-instruments-s-a--senior-pdgs-fullstack-developer-krakow-python'),
  ('justjoin', 'creotech-instruments-s-a--senior-pdgs-fullstack-developer-krakow-javascript'),
  ('solidjobs', '08b4c329-d942-4a4c-b173-d21b20f9ffb0'),
  ('justjoin', '7n-sp-z-o-o--fullstack-developer-react-kotlin-java---frontend-oriented-gdansk-javascript'),
  ('bulldog', '255409-mid-senior-full-stack-developer-net-react-warsaw-polcode-sp-z-o-o'),
  ('solidjobs', 'bcb3b46e-6b7b-4f5b-9bad-4f8b6975d91d'),
  ('justjoin', 'codetwo-sp-z-o-o-sp-k--web-developer-jelenia-gora-javascript-3c49dc90'),
  ('justjoin', 'on-the-spot-development-senior-full-stack-developer-react-node-js--warszawa-javascript'),
  ('justjoin', 'creotech-instruments-s-a--pdgs-fullstack-developer-regular--krakow-javascript'),
  ('justjoin', 'creotech-instruments-s-a--pdgs-fullstack-developer-regular--krakow-java'),
  ('justjoin', 'creotech-instruments-s-a--pdgs-fullstack-developer-regular--krakow-python'),
  ('justjoin', 'n-ix-senior-full-stack-react-python-engineer-krakow-python'),
  ('justjoin', 'sni-senior-fullstack-developer-node-js-react--warszawa-javascript'),
  ('justjoin', 'itelence-fullstack-developer---react-next-js-python-warszawa-javascript'),
  ('justjoin', 'andersen-frontend-ui-engineer-with-german-munich-javascript'),
  ('justjoin', 'sni-senior-react-developer-warszawa-javascript'),
  ('justjoin', 'link-group-senior-frontend-engineer-warszawa-javascript'),
  ('justjoin', 'link-group-senior-frontend-engineer-warszawa-javascript-9bf82ffb'),
  ('nofluff', 'senior-frontend-engineer-link-group-Warszawa-2'),
  ('justjoin', 'link-group-lead-full-stack-engineer-node-js-react-next-js--warszawa-javascript'),
  ('nofluff', 'lead-full-stack-engineer-node-js-react-next-js-link-group-Warszawa-1'),
  ('justjoin', 'pretius-software-engineer---backend-scala-kotlin--warszawa-java'),
  ('justjoin', 'sorigo-senior-java-developer-developerka-warszawa-java'),
  ('justjoin', 'bluebinary-io-senior-frontend-vue-architect-tech-lead-wroclaw-javascript'),
  ('eldorado', '439550'),
  ('justjoin', 'flyps-senior-fullstack-engineer-poznan-javascript'),
  ('justjoin', 'altimi-fullstack-developer-react-node-js--wroclaw-javascript-f0180afb'),
  ('solidjobs', 'ebaf7eb0-d74d-42d2-bb3a-8d077f0a5ae4'),
  ('eldorado', '435700'),
  ('justjoin', 'comm1t-senior-fullstack-engineer-python--warszawa-python-0b4ee9c6'),
  ('eldorado', '438024'),
  ('eldorado', '438028'),
  ('eldorado', '438029'),
  ('justjoin', 'altimetrik-poland-senior-react-developer-krakow-javascript-c6d7cd5b'),
  ('eldorado', '441300'),
  ('eldorado', '438041'),
  ('justjoin', 'publink-senior-product-engineer-react-typescript-net--poznan-net'),
  ('justjoin', 'edugo-p-s-a--engineering-manager-hands-on-w-react-i-typescript--rzeszow-pm'),
  ('nofluff', 'technical-delivery-manager-net-react-link-group-Warszawa-2'),
  ('eldorado', '449742'),
  ('justjoin', 'link-group-senior-fullstack-developer-net-react-warszawa-net'),
  ('justjoin', 'link-group-senior-fullstack-developer---net-react-warszawa-net'),
  ('nofluff', 'senior-fullstack-developer-net-react-link-group-Warszawa-6'),
  ('eldorado', '449737'),
  ('justjoin', 'from-poland-with-dev-senior-react-native-dev-us-vr-startup-krakow-mobile-97f3b291'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-databricks-python-fastapi--poznan-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-databricks-python-fastapi--krakow-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-databricks-python-fastapi--gdansk-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-databricks-python-fastapi--katowice-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-databricks-python-fastapi--lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-databricks-python-fastapi--wroclaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer---python-fastapi-react-typescript-warsaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--poznan-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer---python-fastapi-react-typescript-lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--wroclaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--katowice-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer---python-fastapi-react-typescript-krakow-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--gdansk-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer---python-fastapi-react-typescript-gdansk-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--warsaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer---python-fastapi-react-typescript-poznan-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer---python-fastapi-react-typescript-wroclaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-typescript--krakow-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-sql-katowice-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-sql-wroclaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-sql-poznan-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-sql-gdansk-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-sql-lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-python-fastapi-react-sql-krakow-python'),
  ('justjoin', 'epam-systems-senior-power-platform-engineer-warsaw-devops-e89dd3ac'),
  ('justjoin', 'epam-systems-senior-power-platform-engineer-lodz-devops-78f6da9a'),
  ('justjoin', 'epam-systems-senior-power-platform-engineer-poznan-devops-bbe78cca'),
  ('justjoin', 'epam-systems-senior-power-platform-engineer-wroclaw-devops-11208138'),
  ('justjoin', 'epam-systems-senior-power-platform-engineer-gdansk-devops-00f0f32e'),
  ('justjoin', 'epam-systems-senior-power-platform-engineer-katowice-devops-cb91d9ef'),
  ('justjoin', 'epam-systems-senior-full-stack-engineer---python-aws-with-react-lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-engineer---python-aws-with-react-warsaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-engineer---python-aws-with-react-wroclaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-engineer---python-aws-with-react-katowice-python'),
  ('justjoin', 'epam-systems-senior-full-stack-engineer---python-aws-with-react-krakow-python'),
  ('justjoin', 'epam-systems-senior-full-stack-engineer---python-aws-with-react-poznan-python'),
  ('eldorado', '441521'),
  ('justjoin', 'epam-systems-lead-full-stack-developer-gdansk-python'),
  ('justjoin', 'epam-systems-lead-full-stack-developer-poznan-python'),
  ('justjoin', 'epam-systems-lead-full-stack-developer-lodz-python'),
  ('eldorado', '442555'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-postgresql-opensearch-databricks--poznan-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-postgresql-opensearch-databricks--lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-postgresql-opensearch-databricks--krakow-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-postgresql-opensearch-databricks--warsaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-postgresql-opensearch-databricks--katowice-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-postgresql-opensearch-databricks--wroclaw-python'),
  ('justjoin', 'dmtech-polska-senior-fullstack-developer-java-react-z-j-niemieckim-b2b--wroclaw-java-9107ded5'),
  ('justjoin', 'dmtech-polska-senior-fullstack-developer-java-react-z-j-niemieckim-b2b--wroclaw-java-f7fbfbd1'),
  ('justjoin', 'dmtech-polska-senior-fullstack-developer-java-react-z-j-niemieckim-b2b--wroclaw-java-8014c351'),
  ('eldorado', '449063'),
  ('solidjobs', 'bad2e594-51a4-4e0e-8bb0-9a25776fe85f'),
  ('solidjobs', 'e620bb13-687f-4127-84d2-ad6e01c9a8ee'),
  ('solidjobs', '28909769-5cf4-4fcb-a16d-c93493a41d49'),
  ('solidjobs', '1e42f666-b5d2-4019-8a01-61f9f7d81c31'),
  ('solidjobs', 'a81c3066-9d97-47c0-bd3b-4a2489f85222'),
  ('solidjobs', 'cd632066-76d6-4e67-8fea-8cac72e6f31c'),
  ('solidjobs', '0dcb385e-ba51-4e41-b2b3-bebb4c7b1099'),
  ('solidjobs', 'aebb7238-a6ca-435b-afd0-332b252b23f2'),
  ('bulldog', '255532-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '255297-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '255622-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '255599-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '255712-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '256036-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '256034-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '256161-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '256148-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '256431-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '256430-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '256503-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '256498-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '256825-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '256763-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('solidjobs', 'adec016d-aac9-4bd4-a8cd-6e56690f5410'),
  ('solidjobs', '82b79f5a-4306-45f7-94a4-2ca42f4d685e'),
  ('bulldog', '256914-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '257018-senior-frontend-developer-react-react-native-warsaw-teamquest'),
  ('bulldog', '257004-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('bulldog', '257084-senior-frontend-developer-react-react-native-warszawa-teamquest'),
  ('justjoin', 'jit-team-senior-frontend-developer-warszawa-javascript-b6c9adfa'),
  ('eldorado', '439523'),
  ('solidjobs', '8c7b3ed8-bb5d-450c-9d64-4cdbc20d470f'),
  ('solidjobs', 'b97344d4-55cd-4016-88ee-8e8ba925d57e'),
  ('nofluff', 'fullstack-developer-net-react-scalo-Warszawa-4'),
  ('justjoin', 'cyclad-software-developer-react-python-ai--wroclaw-python'),
  ('solidjobs', 'e2b6a1bb-e0f6-46c7-aedd-2b86c087defe'),
  ('eldorado', '444712'),
  ('justjoin', 'scalo-fullstack-developer-java-kotlin-react--wroclaw-java-ffb5748e'),
  ('eldorado', '437891'),
  ('eldorado', '437615'),
  ('justjoin', 'connectis-fullstack-developer-java-react--warszawa-java-cbf6f29e'),
  ('nofluff', 'fullstack-developer-java-react-connectis--Warszawa'),
  ('justjoin', 'itlt-fullstack-developer-typescript-react-node-js--bydgoszcz-javascript'),
  ('justjoin', 'itlt-fullstack-developer-typescript-react-node-js--kielce-javascript'),
  ('justjoin', 'rits-senior-java-developer-warszawa-java-cb36ca3b'),
  ('eldorado', '448223'),
  ('eldorado', '448128'),
  ('justjoin', 'dcg-senior-fullstack-developer-warszawa-javascript-55ddcb70'),
  ('nofluff', 'full-stack-developer-java-kafka-angular-react-mindbox-Warszawa'),
  ('eldorado', '437517'),
  ('nofluff', 'junior-frontend-developer-react-js-masterborn-Remote-5'),
  ('eldorado', '438305'),
  ('bulldog', '255547-senior-fullstack-engineer-luxoft-dxc'),
  ('bulldog', '256442-senior-full-stack-engineer-luxoft-dxc'),
  ('nofluff', 'junior-react-developer-link-group-Remote-4'),
  ('justjoin', 'upvanta-sp-z-o-o--mobile-react-native-developer-warszawa-javascript'),
  ('nofluff', 'mobile-react-native-developer-upvanta-Remote'),
  ('eldorado', '447254'),
  ('eldorado', '438320'),
  ('builtin', '11246080'),
  ('eldorado', '439632'),
  ('bulldog', '256941-staff-lead-fullstack-engineer-frontend-focused-prague-dublin-amsterdam-berlin-buenos-aires-barcelona-mimica'),
  ('bulldog', '256874-senior-frontend-engineer-truv'),
  ('bulldog', '256056-lead-engineer-architect-luxoft-dxc'),
  ('eldorado', '440775'),
  ('bulldog', '255648-software-engineer-paris-belfast-tunis-jakarta-kuala-lumpur-london-brighton-the-flex'),
  ('eldorado', '438749'),
  ('bulldog', '255647-full-stack-engineering-lead-paris-belfast-tunis-jakarta-kuala-lumpur-london-brighton-the-flex'),
  ('eldorado', '438750'),
  ('bulldog', '255646-founding-software-engineer-paris-belfast-tunis-jakarta-kuala-lumpur-london-brighton-the-flex'),
  ('eldorado', '438751'),
  ('bulldog', '255645-full-stack-product-engineer-paris-belfast-tunis-jakarta-kuala-lumpur-london-brighton-the-flex'),
  ('eldorado', '438752'),
  ('eldorado', '438306'),
  ('justjoin', 'edugo-p-s-a--engineering-leader---buduj-platforme-edukacyjna-poznan-pm'),
  ('eldorado', '438309'),
  ('eldorado', '438618'),
  ('nofluff', 'senior-fullstack-engineer-node-react-typescript-link-group-Remote-1'),
  ('justjoin', 'link-group-senior-fullstack-engineer---node-react-typescript-warszawa-javascript'),
  ('nofluff', 'senior-full-stack-php-react-developer-digis-a-fiverr-company-Warsaw'),
  ('justjoin', 'upvanta-sp-z-o-o--senior-software-engineer-net-c-react--wroclaw-net'),
  ('eldorado', '438950'),
  ('eldorado', '438531'),
  ('justjoin', 'xebia-sp-z-o-o---senior-fullstack-engineer-kotlin-react--wroclaw-java'),
  ('justjoin', 'airhelp-full-stack-software-engineer---claiming-experience-krakow-javascript-29e857d9'),
  ('nofluff', 'senior-full-stack-django-react-gcp-vecten-Remote'),
  ('eldorado', '438557'),
  ('justjoin', 'vazco-senior-full-stack-ai-developer-wroclaw-javascript-355bbc2b'),
  ('justjoin', 'vazco-ai-technical-lead-wroclaw-architecture'),
  ('eldorado', '438664'),
  ('eldorado', '438421'),
  ('eldorado', '438502'),
  ('eldorado', '439332'),
  ('eldorado', '440088'),
  ('nofluff', 'wearables-engineer-connectis--Remote'),
  ('nofluff', 'senior-fullstack-developer-react-node-js-c--scalo-Remote'),
  ('eldorado', '438465'),
  ('eldorado', '439118'),
  ('eldorado', '440007'),
  ('eldorado', '438464'),
  ('nofluff', 'full-stack-developer-itfs-Remote'),
  ('solidjobs', '38a7c52d-b250-4ccd-ae6c-de51302f2795'),
  ('eldorado', '439150'),
  ('eldorado', '439147'),
  ('eldorado', '439033'),
  ('eldorado', '438539'),
  ('eldorado', '438568'),
  ('nofluff', 'senior-fullstack-developer-java-react-z-j-angielskim-lub-niemieckim-customer-service-management-b2b-dmtech-Remote'),
  ('justjoin', 'dmtech-polska-senior-fullstack-developer-java-react-z-j-angielskim-lub-niemieckim---customer-service-management-b2b--wroclaw-java-884ceb67'),
  ('eldorado', '449069'),
  ('nofluff', 'senior-fullatack-engineer-java-react-connectis--Warszawa'),
  ('eldorado', '438588'),
  ('eldorado', '438788'),
  ('eldorado', '444288'),
  ('builtin', '11354903'),
  ('eldorado', '438647'),
  ('solidjobs', '638824a0-e939-4145-accb-a04437e14436'),
  ('justjoin', 'edge-one-solutions-sp-z-o-o-senior-frontend-developer-angular-branza-bankowa-warszawa-javascript'),
  ('justjoin', 'pko-bp-finat-programista-net-warszawa-net-8cbe6f32'),
  ('justjoin', 'act-digital-fullstack-developer-warszawa-java-a2762535'),
  ('justjoin', 'act-digital-fullstack-developer-warszawa-net'),
  ('justjoin', 'moondigo-sp-z-o-o--fullstack-developer-java-react--warszawa-java'),
  ('justjoin', 'connectis-react-native-developer-warszawa-mobile-cde7e9f1'),
  ('eldorado', '439252'),
  ('justjoin', 'pretius-senior-react-native-developer-warszawa-mobile'),
  ('justjoin', 'pretius-react-native-developer-warszawa-mobile'),
  ('eldorado', '438677'),
  ('eldorado', '438656'),
  ('justjoin', 'nexio-management-fullstack-developer-java-react-k-m-n--warszawa-java-07c036ab'),
  ('eldorado', '447729'),
  ('eldorado', '439100'),
  ('eldorado', '440031'),
  ('justjoin', 'airslate-senior-fullstack-engineer---ai-wroclaw-ai'),
  ('eldorado', '439220'),
  ('eldorado', '439314'),
  ('eldorado', '439176'),
  ('eldorado', '439842'),
  ('justjoin', 'edugo-p-s-a--engineering-manager---100-zdalnie-warszawa-pm'),
  ('eldorado', '439537'),
  ('eldorado', '439480'),
  ('eldorado', '440069'),
  ('eldorado', '446827'),
  ('justjoin', 'orange-polska-fullstack-developer---system-zarzadzania-kluczami-kwantowymi-kme-m-k--warszawa-python'),
  ('eldorado', '439697'),
  ('eldorado', '439700'),
  ('eldorado', '439455'),
  ('eldorado', '439452'),
  ('eldorado', '441287'),
  ('eldorado', '441328'),
  ('nofluff', 'middle-fullstack-engineer-kotlin-react-xebia-Rzeszów'),
  ('justjoin', 'xebia-sp-z-o-o---middle-fullstack-engineer-kotlin-react--wroclaw-java'),
  ('eldorado', '447429'),
  ('eldorado', '440198'),
  ('nofluff', 'senior-react-developer-avenga-agencja-pracy-nr-kraz-8448-Warszawa'),
  ('eldorado', '440041'),
  ('eldorado', '440329'),
  ('eldorado', '443417'),
  ('justjoin', 'itds-senior-react-ui-engineer---ai-integrated-component-libraries-warszawa-javascript'),
  ('justjoin', 'emagine-polska-senior-fullstack-engineer---with-focus-on-frontend-stockholm-city-java'),
  ('justjoin', 'hellofresh--senior-mobile-product-engineer-intelligent-platforms-all-genders--warszawa-mobile'),
  ('eldorado', '442881'),
  ('justjoin', 'vistulo-senior-react-developer-with-fixed-income-experience-warszawa-javascript'),
  ('justjoin', 'act-digital-drupal-software-engineer-warszawa-php'),
  ('justjoin', 'b3-consulting-poland-senior-fullstack-engineer-java-kotlin-react--warszawa-java'),
  ('justjoin', 'b3-consulting-poland-fullstack-engineer-java-kotlin-react--warszawa-java'),
  ('justjoin', 'talent-hunter-sp-z-o-o--senior-fullstack-software-developer-warszawa-python'),
  ('eldorado', '441269'),
  ('eldorado', '441260'),
  ('eldorado', '440921'),
  ('eldorado', '440772'),
  ('eldorado', '441249'),
  ('eldorado', '441495'),
  ('eldorado', '442270'),
  ('eldorado', '441420'),
  ('eldorado', '441682'),
  ('eldorado', '441797'),
  ('eldorado', '441798'),
  ('eldorado', '441801'),
  ('eldorado', '441799'),
  ('eldorado', '441800'),
  ('eldorado', '441806'),
  ('eldorado', '441811'),
  ('eldorado', '441749'),
  ('eldorado', '440832'),
  ('eldorado', '442063'),
  ('justjoin', 'apreel-senior-fullstack-developer-net-react--warszawa-net'),
  ('nofluff', 'senior-fullstack-developer-net-react-apreel-Warszawa'),
  ('eldorado', '442449'),
  ('justjoin', 'in4ge-sp-z-o-o--ai-engineer-with-frontend-react-angular--warszawa-ai'),
  ('eldorado', '443148'),
  ('justjoin', 'blazity-sp-z-o-o--senior-full-stack-developer-react-next-js-typescript-warszawa-javascript'),
  ('eldorado', '442059'),
  ('eldorado', '441964'),
  ('eldorado', '441967'),
  ('eldorado', '441867'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-katowice-python-f1b66ae6'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-warsaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-krakow-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-wroclaw-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-krakow-python-97a38403'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-wroclaw-python-08d4dd57'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-poznan-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-katowice-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-poznan-python-a9a66819'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-warsaw-python-302f5566'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-gdansk-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-lodz-python'),
  ('justjoin', 'epam-systems-senior-full-stack-developer-lodz-python-e9a25e8d'),
  ('bulldog', '256368-ui-developer-warsaw-devire'),
  ('eldorado', '442354'),
  ('eldorado', '447471'),
  ('eldorado', '442345'),
  ('eldorado', '443382'),
  ('solidjobs', 'd5f369ac-438c-44c4-b9e4-099d33188cc2'),
  ('justjoin', 'zaven-senior-net-developer-wroclaw-net-b5805061'),
  ('justjoin', 'remodevs-senior-fullstack-developer-wroclaw-javascript-545c9f2d'),
  ('justjoin', 'dna-technology-senior-fullstack-engineer-ai-product--lodz-javascript-c5b4c827'),
  ('justjoin', 'dna-technology-senior-fullstack-engineer-ai-product--lodz-python-20a7482b'),
  ('justjoin', 'speednet-tech-lead-solution-architect-gdansk-architecture'),
  ('justjoin', 'blockydevs-sp-z-o-o--senior-fullstack-developer-warszawa-javascript-18d65e63'),
  ('justjoin', 'senovo-it-full-stack-developer-net-react-ai---remote-b2b-warszawa-net-4997d3b3'),
  ('justjoin', 'dreryk-senior-fullstack-developer-f-m---java-react-krakow-java-d3b8f7fb'),
  ('justjoin', 'blazity-sp-z-o-o--mid-full-stack-developer-react-next-js-typescript-warszawa-javascript'),
  ('eldorado', '446546'),
  ('justjoin', 'ideamotive-senior-fullstack-developer-net-react--warszawa-net'),
  ('justjoin', 'b3-consulting-poland-frontend-engineer-react-typescript--warszawa-javascript'),
  ('justjoin', 'upvanta-sp-z-o-o--fullstack-developer-typescript-react--warszawa-javascript'),
  ('eldorado', '443590'),
  ('eldorado', '443690'),
  ('eldorado', '443715'),
  ('eldorado', '442917'),
  ('eldorado', '443727'),
  ('justjoin', 'dcg-senior-frontend-developer-react-next-js--warszawa-javascript'),
  ('eldorado', '443729'),
  ('eldorado', '442938'),
  ('justjoin', 'pekao-conext-programista-frontend-senior-warszawa-javascript'),
  ('justjoin', 'randlab-frontend-developer-react-k-m-n--warszawa-javascript-3c955a9d'),
  ('eldorado', '443174'),
  ('justjoin', 'randlab-frontend-developer-react-k-m-n--warszawa-javascript-e2ba636b'),
  ('eldorado', '449140'),
  ('eldorado', '443177'),
  ('eldorado', '443072'),
  ('justjoin', 'in4ge-sp-z-o-o--full-stack-engineer-python-javascript---cloud-data-platforms-warszawa-python'),
  ('eldorado', '443190'),
  ('eldorado', '443191'),
  ('eldorado', '443010'),
  ('justjoin', 'in4ge-sp-z-o-o--full-stack-developer-node-js-python--warszawa-javascript'),
  ('eldorado', '443207'),
  ('eldorado', '443743'),
  ('eldorado', '443744'),
  ('eldorado', '443015'),
  ('eldorado', '443084'),
  ('justjoin', 'sii-fullstack-java-engineer---aml-kyc-reporting-f-m-x--lublin-java'),
  ('eldorado', '442916'),
  ('eldorado', '443628'),
  ('eldorado', '444274'),
  ('justjoin', 'zadbano-sa-tech-lead-manager---platform-delivery-reliability-warszawa-javascript'),
  ('eldorado', '444326'),
  ('eldorado', '444219'),
  ('eldorado', '444475'),
  ('eldorado', '443932'),
  ('justjoin', 'antal-sp-z-o-o--senior-full-stack-developer-python-ai--warszawa-python'),
  ('eldorado', '443819'),
  ('eldorado', '444137'),
  ('justjoin', 'dcg-senior-frontend-developer-react-typescript--warszawa-javascript'),
  ('eldorado', '444040'),
  ('eldorado', '449705'),
  ('nofluff', 'senior-frontend-developer-react-typescript-dcg-Warszawa'),
  ('eldorado', '444041'),
  ('eldorado', '444135'),
  ('justjoin', 'dcg-senior-ui-ux-design-front-end-lead-warszawa-javascript'),
  ('justjoin', 'allegro-front-end-software-engineer-2-advertising--warszawa-javascript'),
  ('eldorado', '444064'),
  ('eldorado', '444575'),
  ('eldorado', '445269'),
  ('eldorado', '445159'),
  ('justjoin', 'connectis-fullstack-developer-react-java--warszawa-java-4ca7d870'),
  ('nofluff', 'fullstack-developer-react-java-connectis--Remote-2'),
  ('eldorado', '444621'),
  ('justjoin', 'connectis-fullstack-ai-engineer-warszawa-ai'),
  ('eldorado', '444154'),
  ('justjoin', 'connectis-ai-engineer-warszawa-ai-bc8fe0ca'),
  ('eldorado', '444263'),
  ('justjoin', 'scalo-fullstack-developer-python-ai--warszawa-python'),
  ('justjoin', 'antal-sp-z-o-o--mid-full-stack-developer-python-ai--warszawa-python'),
  ('justjoin', 'primaris-services-sp-z-o-o--senior-fullstack-python-ai-developer-warszawa-python'),
  ('eldorado', '445151'),
  ('eldorado', '448255'),
  ('justjoin', 'emagine-polska-lead-net-developer-london-net'),
  ('justjoin', 'kalepa-full-stack-engineer-europe--warszawa-python'),
  ('eldorado', '445097'),
  ('justjoin', 'inter-cars-s-a--fullstack-software-engineer-warszawa-java-2299b956'),
  ('eldorado', '446195'),
  ('eldorado', '446142'),
  ('eldorado', '445336'),
  ('builtin', '11374056'),
  ('justjoin', 'lumicode-sp-z-o-o-pentacomp-group--senior-genai-full-stack-developer-python-react--warszawa-python'),
  ('justjoin', 'lumicode-sp-z-o-o-pentacomp-group--genai-developer-python-react--warszawa-python'),
  ('eldorado', '445291'),
  ('eldorado', '444881'),
  ('eldorado', '445010'),
  ('eldorado', '445023'),
  ('justjoin', 'b2bnetwork-fullstack-developer-f-m--warszawa-java'),
  ('eldorado', '449541'),
  ('eldorado', '444769'),
  ('eldorado', '448248'),
  ('justjoin', 'yard-corporate-senior-ux-engineer-warszawa-ux-f8943d8c'),
  ('justjoin', 'softblue-intechhouse--regular-fullstack-developer---react-python-k-m--bydgoszcz-javascript'),
  ('eldorado', '445374'),
  ('eldorado', '447489'),
  ('eldorado', '447676'),
  ('eldorado', '446755'),
  ('eldorado', '447699'),
  ('eldorado', '447724'),
  ('eldorado', '447730'),
  ('eldorado', '445715'),
  ('eldorado', '446060'),
  ('nofluff', 'senior-fullstack-developer-python-react-scalo-Remote-2'),
  ('eldorado', '447744'),
  ('eldorado', '446329'),
  ('nofluff', 'react-developer-electron-scalo-Remote'),
  ('nofluff', 'senior-full-stack-engineer-python-react-softserve-Remote'),
  ('eldorado', '447025'),
  ('nofluff', 'senior-react-developer-technical-leadership-belvedere-recruitment-Warsaw'),
  ('nofluff', 'full-stack-engineer-box-Warsaw'),
  ('nofluff', 'frontend-react-engineer-square-one-resources-Warsaw'),
  ('nofluff', 'ai-full-stack-product-engineer-react-typescript-warsaw-onsite-square-one-resources-Warsaw'),
  ('eldorado', '446151'),
  ('eldorado', '445982'),
  ('justjoin', 'cloudfide-spolka-z-ograniczona-odpowiedzialnoscia-fullstack-developer-python-react--warszawa-python'),
  ('justjoin', 'scalo-fullstack-developer-react-java-kotlin--wroclaw-java'),
  ('eldorado', '448089'),
  ('eldorado', '448809'),
  ('nofluff', 'senior-ai-engineer-node-js-react-iteamly-Remote'),
  ('eldorado', '448093'),
  ('eldorado', '448095'),
  ('eldorado', '447867'),
  ('eldorado', '447947'),
  ('eldorado', '447905'),
  ('eldorado', '449246'),
  ('eldorado', '448884'),
  ('eldorado', '448700'),
  ('eldorado', '448807'),
  ('nofluff', 'full-stack-react-python-link-group-Remote'),
  ('eldorado', '449125'),
  ('bulldog', '256992-net-software-engineer-warsaw-esmetric-group-sp-z-o-o'),
  ('eldorado', '448574'),
  ('eldorado', '448449'),
  ('eldorado', '448479'),
  ('eldorado', '448537'),
  ('eldorado', '448388'),
  ('eldorado', '448032'),
  ('eldorado', '448373'),
  ('eldorado', '449588'),
  ('eldorado', '450190'),
  ('eldorado', '449523'),
  ('eldorado', '448688'),
  ('nofluff', 'senior-fullstack-engineer-net-react-spyrosoft-Remote'),
  ('eldorado', '449487'),
  ('eldorado', '449560'),
  ('eldorado', '449561'),
  ('eldorado', '449562'),
  ('eldorado', '448922'),
  ('eldorado', '448949'),
  ('eldorado', '448953'),
  ('eldorado', '448728'),
  ('eldorado', '448965'),
  ('eldorado', '450148'),
  ('eldorado', '448984'),
  ('justjoin', 'in4ge-sp-z-o-o--senior-front-end-developer-react-angular--warszawa-javascript'),
  ('eldorado', '450224'),
  ('eldorado', '450100'),
  ('eldorado', '449570'),
  ('justjoin', 'in4ge-sp-z-o-o--mobile-application-developer-react-native-ios-android--warszawa-mobile'),
  ('eldorado', '450223'),
  ('eldorado', '450185'),
  ('eldorado', '449721'),
  ('eldorado', '450269'),
  ('eldorado', '449818'),
  ('eldorado', '449982'),
  ('eldorado', '449728'),
  ('eldorado', '449820'),
  ('eldorado', '449824'),
  ('eldorado', '449963')
), gone as (
  delete from public.offers o using dupes d
  where o.src = d.src and o.id = d.id
  returning o.src, o.id, o.title, o.company, o.seniority, o.remote, o.url, o.first_seen
)
insert into public.offers_removed_dupes (src, id, title, company, seniority, remote, url, first_seen)
select src, id, title, company, seniority, remote, url, first_seen from gone on conflict do nothing;

select
  (select count(*) from public.offers)              as offers_left,
  (select count(*) from public.offers_removed_dupes) as moved_to_backup,
  (select count(*) from public.offers where src !~ '^[a-z]+$') as broken_sources_left;

commit;
